name: Deploy via SSM

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [event-on-demand-build]

jobs:
  deploy-ssm:
    name: SSM Deployment
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_NAME }}

      - name: Deploy to EC2
        env:
          GRAFANA_URL: ${{ secrets.GRAFANA_REMOTE_WRITE_URL }}
          GRAFANA_USER: ${{ secrets.GRAFANA_REMOTE_WRITE_USER }}
          GRAFANA_KEY: ${{ secrets.GRAFANA_REMOTE_WRITE_KEY }}
        run: |
          echo "🔍 Finding Instance with tag 'Monitoring=true'..."
          
          # 1. Dynamic Discovery
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Monitoring,Values=true" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output text)

          if [ -z "$INSTANCE_ID" ]; then
            echo "❌ Error: No running instance found with tag 'Monitoring=true'"
            exit 1
          fi
          
          echo "✅ Found Target: $INSTANCE_ID"

          # 2. Define Commands (The Self-Healing Way)
          # Includes Bootstrap (Clone if missing) + Permission Fixes + Deployment
          jq -n \
            --arg url "$GRAFANA_URL" \
            --arg user "$GRAFANA_USER" \
            --arg key "$GRAFANA_KEY" \
            --arg cmd1 "if [ ! -d /home/ubuntu/monitoring ]; then echo '🌱 Repo missing. Cloning...'; sudo git clone https://github.com/ashish-soni-org/Monitoring.git /opt/monitoring; fi" \
            --arg cmd2 "cd /opt/monitoring" \
            --arg cmd3 "echo '⬇️ Fetching latest code...'" \
            --arg cmd4 "sudo git fetch origin main" \
            --arg cmd5 "sudo git reset --hard origin/main" \
            --arg cmd6 "sudo git clean -fd" \
            --arg cmd7 "echo '🔧 Injecting Secrets...'" \
            --arg cmd8 "mkdir -p prometheus/secrets" \
            --arg cmd9 "echo \"$key\" > prometheus/secrets/api_key" \
            --arg cmd10 "sed -i \"s|\\\${GRAFANA_REMOTE_WRITE_URL}|$url|g\" prometheus/prometheus.yml" \
            --arg cmd11 "sed -i \"s|\\\${GRAFANA_REMOTE_WRITE_USER}|$user|g\" prometheus/prometheus.yml" \
            --arg cmd12 "echo '🔧 Fixing Grafana permissions...'" \
            --arg cmd13 "sudo chown -R 472:472 grafana" \
            --arg cmd14 "echo '🐳 Updating Stack...'" \
            --arg cmd15 "sudo docker compose pull" \
            --arg cmd16 "sudo docker compose up -d --remove-orphans --force-recreate" \
            --arg cmd17 "sudo docker image prune -f" \
            '{"commands": [$cmd1, $cmd2, $cmd3, $cmd4, $cmd5, $cmd6, $cmd7, $cmd8, $cmd9, $cmd10, $cmd11, $cmd12, $cmd13, $cmd14, $cmd15, $cmd16, $cmd17]}' > ssm_payload.json

          # 3. Execute SSM Command
          echo "⚡ Sending Command to SSM..."
          SH_COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=$INSTANCE_ID" \
            --comment "GitHub Actions Deployment" \
            --parameters file://ssm_payload.json \
            --query "Command.CommandId" \
            --output text)

          echo "⏳ Execution Started. Command ID: $SH_COMMAND_ID"

          # 4. Polling Loop
          while true; do
            STATUS=$(aws ssm list-command-invocations \
              --command-id "$SH_COMMAND_ID" \
              --details \
              --query "CommandInvocations[0].Status" \
              --output text)
            
            echo "Status: $STATUS"

            if [[ "$STATUS" == "Success" ]]; then
              echo "✅ Deployment Successful!"
              exit 0
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
              echo "❌ Deployment Failed. Fetching logs..."
              aws ssm get-command-invocation \
                --command-id "$SH_COMMAND_ID" \
                --instance-id "$INSTANCE_ID" \
                --query "StandardErrorContent" \
                --output text
              exit 1
            fi
            
            sleep 5
          done